### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/forxpy#42]
> **Congratulations on finishing milestone 3!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, please feel free to ask questions in this issue thread.

---

### 1. Write test cases and code iteratively
rubric={accuracy:20,quality:10,mechanics:10}

Well done!

Comments: Zero fails!

### 1. GitHub actions workflow for continuous integration
rubric={mechanics:10}

Well done!

### 2. GitHub actions workflow for continuous deployment
rubric={mechanics:10}
 
Well done!

### 3. Documentation
rubric={reasoning:10}

- [ ] There is no link on `GitHub` or in the `README.md` to ReadTheDocs - **-2 reasoning**

## 4. Specific expectations for this milestone 
rubric={mechanics:10}

-  [ ] There are not issues in the project board added during this milestone. - **mechanics -2**

- [ ] There isn't a milestone called `milestone3`. - **mechanics -2**

## 5. Submission instructions
rubric={mechanics:10}

Well done!

**Comment by dhruvinishar** [comment]
Thank you @negsadr for such a prompt review! 
We did include a link to the readthedocs in our about section. 
<img width="567" alt="Screenshot 2023-02-05 at 8 53 11 PM" src="https://user-images.githubusercontent.com/55327454/216886605-75118495-6794-45c9-a82b-b7e94f7d04cf.png">

**Comment by negsadr** [comment]
@dhruvinishar thanks for your message!
I modified the grading accordingly!
