### ISSUE TITLE
Milestone 4 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/forxpy#43]
Congratulations on finishing milestone 4! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.

Python

Python issues are still open. 

CICD is working properly!

The Python package review has been opened and is not using the template

Rstudio

- [ ] Why are there still branches that exists that aren’t deleted if the package is finished? -1 Mechanics

- [ ] The link to the website created with pkgdown or it is not possible to be easily found for an user - -5 reasoning

- [ ] Milestone 4 is not complete 66% complete, and there is no project board added for this milestone -1, -2

- [ ] There are no issues in the project board added during this milestone. - mechanics -2

CICD is working properly!

The RStudio package review has been opened and is not using the template.

I can install the package from github! 

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.
